version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: ctrl-fleet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ctrl_fleet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: ctrl-fleet-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: ctrl-fleet-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ctrl_fleet
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    volumes:
      - ./back:/app
    working_dir: /app
    command: ./mvnw spring-boot:run

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: ctrl-fleet-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host

volumes:
  postgres_data: